### PR TITLE
crates/sel4-capdl-initializer: fix compile error

### PR DESCRIPTION
**Pull request by Ivan-Velickovic**
Compilation error introduced in https://github.com/seL4/rust-sel4/pull/106.

### CODE REVIEW

**Comment by nspin** [comment]
Sorry about this 😬

I will add a test that covers MCS (and release) code paths in the CapDL code.

Thanks for the fix!

**Comment by Ivan-Velickovic** [comment]
> I will add a test that covers MCS (and release) code paths in the CapDL code.

Thanks, that would be convenient! (for my own patches as well haha)
